//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMP.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectLogs = new HashSet<ProjectLog>();
            this.ProjectSettings = new HashSet<ProjectSetting>();
            this.ProjectUsers = new HashSet<ProjectUser>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string TItle { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ProjectLog> ProjectLogs { get; set; }
        public virtual ICollection<ProjectSetting> ProjectSettings { get; set; }
        public virtual ICollection<ProjectUser> ProjectUsers { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
