//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMP.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Subtasks = new HashSet<Subtask>();
            this.TaskComments = new HashSet<TaskComment>();
            this.TaskLogs = new HashSet<TaskLog>();
            this.ProjectUsers = new HashSet<ProjectUser>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public byte Status { get; set; }
        public int ProjectId { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<Subtask> Subtasks { get; set; }
        public virtual ICollection<TaskComment> TaskComments { get; set; }
        public virtual ICollection<TaskLog> TaskLogs { get; set; }
        public virtual ICollection<ProjectUser> ProjectUsers { get; set; }
    }
}
