//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMP.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ProjectLogs = new HashSet<ProjectLog>();
            this.ProjectUsers = new HashSet<ProjectUser>();
            this.Subtasks = new HashSet<Subtask>();
            this.TaskComments = new HashSet<TaskComment>();
            this.TaskLogs = new HashSet<TaskLog>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Avatar { get; set; }
    
        public virtual ICollection<ProjectLog> ProjectLogs { get; set; }
        public virtual ICollection<ProjectUser> ProjectUsers { get; set; }
        public virtual ICollection<Subtask> Subtasks { get; set; }
        public virtual ICollection<TaskComment> TaskComments { get; set; }
        public virtual ICollection<TaskLog> TaskLogs { get; set; }
    }
}
